version: '2'

networks:
  proxy:
    external:
      name: proxy

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8083:80"
    expose:
      - "80"
    volumes:
      - .:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: 3dpoetryeditor.art,www.3dpoetryeditor.art
      LETSENCRYPT_HOST: 3dpoetryeditor.art,www.3dpoetryeditor.art
      LETSENCRYPT_EMAIL: davidjonasdesign@gmail.com
    networks:
      - default
      - proxy
